version: '3.8'
services:
  hugo:
    image: hugomods/hugo:latest
    ports:
      - "1313:1313"
    volumes:
      - .:/src
    working_dir: /src
    command: hugo server --bind 0.0.0.0 --port 1313 --baseURL http://192.168.50.247:1313 --appendPort=false
    environment:
      - HUGO_WATCH=true
      - HUGO_REFRESH_TIME=1
      - HUGO_THEME=ananke
      - HUGO_BASEURL=http://192.168.50.247:1313
      - TZ="Asia/Shanghai"  
    restart: unless-stopped
