baseURL = 'https://neican.huangzuomin.com/'
languageCode = 'zh-cn'
defaultContentLanguage = 'zh-cn'
title = 'AI内参'
theme = 'ananke'
disqusShortname = ""
googleAnalytics = ""

# 语言配置
[languages]
  [languages.zh-cn]
    languageCode = 'zh-cn'
    languageName = '中文'
    title = 'AI内参'
    weight = 1

# 忽略 Synology NAS 系统文件
ignoreFiles = [
  "@eaDir",
  "@SynoEAStream", 
  "@SynoResource",
  "@tmp",
  "\\.DS_Store$",
  "Thumbs\\.db$"
]

# 忽略原始 HTML 警告
ignoreLogs = ['warning-goldmark-raw-html']


# 允许原始 HTML
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      hardWraps = false
      xhtml = false
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = false
  [markup.highlight]
    style = "github"
    lineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNumbersInTable = true
    noClasses = true
    tabWidth = 4

# Ananke 主题配置
[params]
  description = "AI领域的深度分析和最新资讯，专注人工智能技术发展和行业动态"
  author = "温故智新AIGC实验室"
  twitter = ""
  facebook = ""
  youtube = ""
  instagram = ""
  github = "huangzuomin"
  gitlab = ""
  linkedin = ""
  # 启用搜索功能
  ananke_search_index = true
  # 显示阅读时间
  show_reading_time = false
  # 启用评论
  commentoEnable = false
  # 自定义 CSS
  custom_css = ["css/custom.css", "css/article-enhancements.css"]
  # 首页显示的文章数量
  recent_posts_number = 12
  # 启用社交分享
  socialShare = true
  # 背景颜色（可选）
  background_color_class = "bg-black"
  # 文本颜色（可选）
  text_color_class = "white"
  # 特色图片
  featured_image = "/img/featured-bg.png"
  site_logo = "/logo/logo.png"
  # 阅读更多按钮文字
  read_more_copy = "阅读全文"

# Ananke 主题社交分享配置
[params.ananke.social.share]
  disable_share = false
  networks = ["twitter", "weibo", "weixin"]

[params.ananke.social.networks]
  [params.ananke.social.networks.twitter]
    slug = "x-twitter"
    icon = "x-twitter"
    label = "X"
    share = true
    link = "https://twitter.com/intent/tweet/?text={text} - {summary}&url={url}"
    [params.ananke.social.networks.twitter.particles]
      text = "{title}"
      summary = "{summary}"
      url = "{url}"
  
  [params.ananke.social.networks.weibo]
    slug = "weibo"
    icon = "weibo"
    label = "Weibo"
    share = true
    link = "http://service.weibo.com/share/share.php?title={title} - {summary}&url={url}"
    [params.ananke.social.networks.weibo.particles]
      title = "{title}"
      summary = "{summary}"
      url = "{url}"
  
  [params.ananke.social.networks.weixin]
    slug = "weixin"
    icon = "weixin"
    label = "Weixin"
    share = true
    link = "javascript:void(0)"
    onclick = "showWeixinQR"
    [params.ananke.social.networks.weixin.particles]
      title = "{title}"
      url = "{url}"

# 分页配置
[pagination]
  pagerSize = 12

# 分类法配置
[taxonomies]
  category = "main_topics"
  tag = "tags"
  author = "authors"

# 输出格式
[outputs]
  home = ["HTML", "RSS", "JSON"]



# 菜单配置
[[menus.main]]
name = "首页"
url = "/"
weight = 10

[[menus.main]]
name = "洞察"
url = "/insights/"
weight = 20

[[menus.main]]
name = "早报"
url = "/morningnews/"
weight = 30

[[menus.main]]
name = "日报"
url = "/newspaper/"
weight = 40

[[menus.main]]
name = "主题探索"
url = "/explore/"
weight = 50

[[menus.main]]
name = "关于"
url = "/about/"
weight = 60