baseURL = 'https://neican.huangzuomin.com/'
languageCode = 'zh-cn'
defaultContentLanguage = 'zh-cn'
title = 'AI内参'
theme = 'ananke'
disqusShortname = ""
googleAnalytics = ""

# 语言配置
[languages]
  [languages.zh-cn]
    languageCode = 'zh-cn'
    languageName = '中文'
    title = 'AI内参'
    weight = 1

# 忽略 Synology NAS 系统文件
ignoreFiles = [
  "@eaDir",
  "@SynoEAStream", 
  "@SynoResource",
  "@tmp",
  "\\.DS_Store$",
  "Thumbs\\.db$"
]

# 忽略原始 HTML 警告
ignoreLogs = ['warning-goldmark-raw-html']


# 允许原始 HTML
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Ananke 主题配置
[params]
  description = "AI领域的深度分析和最新资讯，专注人工智能技术发展和行业动态"
  author = "温故智新AIGC实验室"
  twitter = ""
  facebook = ""
  youtube = ""
  instagram = ""
  github = "huangzuomin"
  gitlab = ""
  linkedin = ""
  # 启用搜索功能
  ananke_search_index = true
  # 显示阅读时间
  mainSections = ["articles"]
  show_reading_time = false
  # 启用评论
  commentoEnable = false
  # 自定义 CSS
  custom_css = ["css/custom.css", "css/article-enhancements.css"]
  # 首页显示的文章数量
  recent_posts_number = 12
  # 启用社交分享
  socialShare = true
  # 背景颜色（可选）
  background_color_class = "bg-black"
  # 文本颜色（可选）
  text_color_class = "white"
  # 特色图片
  featured_image = "/img/featured-bg.png"

# 分页配置
[pagination]
  pagerSize = 12

# 分类法配置
[taxonomies]
  category = "main_topics"
  tag = "tags"
  author = "authors"

# 输出格式
[outputs]
  home = ["HTML", "RSS", "JSON"]



# 菜单配置
[[menus.main]]
name = "首页"
url = "/"
weight = 10

[[menus.main]]
name = "洞察"
url = "/articles/"
weight = 20

[[menus.main]]
name = "综述"
url = "/Summary/"
weight = 30

[[menus.main]]
name = "主题探索"
url = "/explore/"
weight = 40

[[menus.main]]
name = "关于"
url = "/about/"
weight = 60